POST http://localhost:5000/api/board
Content-Type: application/json

{
  "title": "Testing Board",
  "description": "THIS BOARD IS FOR TESTING PURPOSES",
  "userId": "5e925566c84df16e61326794"
}

###

GET http://localhost:5000/api/board
Content-Type: application/json

###

GET http://localhost:5001/api/board/5e9382650e9b81b4a421869b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikh1bnRlciIsInBhc3N3b3JkIjoicGFzc3dvcmQiLCJpYXQiOjE1ODY4OTkyNjUsImV4cCI6MTU4Njg5OTMyNX0.Dk5i5Xq4L2wguq7XaeTRT9tRZsHaYfGkxbJoWYHKfWo

###

GET http://localhost:5000/api/board/user/5e925566c84df16e61326794
Content-Type: application/json

###
GET http://localhost:5000/api/board/5e7276c97d3c82114dae70c9?key=boardId
Content-Type: application/json

###


