POST http://localhost:5000/api/board
Content-Type: application/json

{
  "title": "post 12",
  "description": "subtitle post 12"
}

###

GET http://localhost:5000/api/board/5e7276c97d3c82114dae70c9
Content-Type: application/json

###

