POST http://localhost:5000/api/card
Content-Type: application/json

{
  "title": "Testing Card",
  "content": "THIS CARD IS FOR TESTING PURPOSES",
  "position": 0,
  "columnId": "5e938839326b93b54c674f43"
}

###

GET http://localhost:5000/api/card/5e938839326b93b54c674f43
Content-Type: application/json

###
GET http://localhost:5000/api/card/column/5e938839326b93b54c674f43
Content-Type: application/json

###

GET http://localhost:5000/api/card/
Content-Type: application/json

###



