POST http://localhost:5001/api/login
Content-Type: application/json

{
  "username": "Hunter",
  "password": "password"
}

###

GET http://localhost:5000/api/user
Content-Type: application/json

###

GET http://localhost:5000/api/board/5e7276c97d3c82114dae70c9
Content-Type: application/json

###
GET http://localhost:5000/api/board/5e7276c97d3c82114dae70c9?key=boardId
Content-Type: application/json

###

