GET http://localhost:3001/api/v1/boards
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjNhM2I0NWNmNDMyODM0ZThmYjliOTYiLCJpYXQiOjE2MDIwNDA0ODAsImV4cCI6MTYwMjA0NDA4MH0.yL6Bs1UdVz0cNOxFjvs3q65eGAFai8u8EI8f9ZuzGKA

###
POST http://localhost:3001/api/v1/boards
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjNhM2I0NWNmNDMyODM0ZThmYjliOTYiLCJpYXQiOjE2MDIwNDA0ODAsImV4cCI6MTYwMjA0NDA4MH0.yL6Bs1UdVz0cNOxFjvs3q65eGAFai8u8EI8f9ZuzGKA

{
  "title": "another board!asdfasdf",
  "workflowId": ""
}

###




