GET http://localhost:3001/api/v1/boards
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjNhM2I0NWNmNDMyODM0ZThmYjliOTYiLCJpYXQiOjE2MDE0Mjk1MDksImV4cCI6MTYwMTQzMzEwOX0.Rf31sRTT7fnHT_mYb_qvNAub4IR1XhUHOJtwbevP5_s

###
POST http://localhost:3001/api/v1/boards
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjNhM2I0NWNmNDMyODM0ZThmYjliOTYiLCJpYXQiOjE2MDE0Mjk1MDksImV4cCI6MTYwMTQzMzEwOX0.Rf31sRTT7fnHT_mYb_qvNAub4IR1XhUHOJtwbevP5_s

{
  "title": "another board!"
}

###




